- name: Variables from files
  hosts: local
  connection: local
  vars_files:
    - vars.yaml
  tasks:
    - name: Include variables from file
      ansible.builtin.debug:
        msg: "Course is {{COURSE}} ,Durartion is {{DURATION}} , trainer is {{TRAINER}}"