- name: Variables
  hosts: local
  connection: local
  vars:
    COURSE: "Devops with AWS"
    DURATION: 120HRS
    TRAINER: SIVAKUMAR
  tasks: 
    - name: Print varable
      vars: 
        COURSE: "ANSIBLE"
      ansible.builtin.debug:
        msg: "Course is {{COURSE}} ,Durartion is {{DURATION}} , trainer is {{TRAINER}}"